- UI có một số phần chưa đúng thiết kế: ICON, khoảng cách giữa các thành phần UI.
- Text mô tả khi hover vào biểu đồ Loại Submit: BA chưa có DEV tự nghĩ => hỏi lại BA.
- UI content Scroll cần confirm lại với PD
